%% crear lista con los archivos a usar
subject_list_EEG= {...
    '1013949.set',...
    '1136580.set',...
    '1208364.set',...
    '1468581.set',...
    '1645050.set',...
    '1848438.set',...
    '1935177.set',...
    '2003970.set',...
    '2009952.set',...
    '2081736muj_NH.set',...
    '2084727.set',...
    '2108655.set',...
    '2117628.set',...
    '9763331.set',...
    '73195803.set',...
    };
%% crear un loop
for s=1:15
    
    STUDY = []; EEG=[]; CURRENTSTUDY= 0; ALLEEG = []; CURRENTSET = [];
    [ALLEEG, EEG, CURRENTSET, ALLCOM] = eeglab;
    %directorio donde están los archivos
    EEG = pop_loadset('filename', [subject_list_EEG{s}], 'filepath', 'D:\Dropbox\Jorge Flores\2023\nuevos analisis EEG humor 2023 SIFT\HH_Study\MNH_chanloc'); 
    [ALLEEG,EEG,CURRENTSET] = eeg_store(ALLEEG, EEG, 0);
    EEG = eeg_checkset(EEG);
    eeglab redraw
    
    %resamplear a 1024
    [ALLEEG, EEG, CURRENTSET] = pop_newset(ALLEEG, EEG, 1,'gui','off'); 
    EEG = pop_resample( EEG, 1024);
    EEG = eeg_checkset( EEG );
    [ALLEEG, EEG, CURRENTSET] = eeg_store( ALLEEG, EEG, 0 );
    eeglab redraw

    %chanloc
    [ALLEEG, EEG] = eeg_store(ALLEEG, EEG, CURRENTSET);
    EEG=pop_chanedit(EEG, 'lookup','C:\Program Files\MATLAB\R2022b\eeglab_current (3)\eeglab2022.1\plugins\dipfit\standard_BEM\elec\\standard_1005.elc');
    EEG = eeg_checkset( EEG );
    [ALLEEG, EEG, CURRENTSET] = eeg_store( ALLEEG, EEG, 0 );
    
    %directorio donde se guardan los archivos
    EEG = pop_saveset(EEG, 'filename', [subject_list_EEG{s}],'filepath','D:\Dropbox\Jorge Flores\2023\nuevos analisis EEG humor 2023 SIFT\HH_Study\MNH_chanloc\chanloc2');
    [ALLEEG EEG] =eeg_store(ALLEEG, EEG, CURRENTSET);
end

