%% CÓDIGO PARA CORTAR ARCHIVOS, para George. 10 Sept 2021

%% crear lista con los archivos a usar MNH
subject_list_EEG= {...
    '1013949.set',...
    '1136580.set',...
    '1208364.set',...
    '1468581.set',...
    '1645050.set',...
    '1848438.set',...
    '1935177.set',...
    '2003970.set',...
    '2009952.set',...
    '2081736muj_NH.set',...
    '2084727.set',...
    '2108655.set',...
    '2117628.set',...
    '9763331.set',...
    '73195803.set',...
    };

%% Segundo, crear un loop que haga todo. 

for s=1:15 
    

STUDY = []; CURRENTSTUDY = 0; ALLEEG = []; EEG=[]; CURRENTSET=[];
[ALLEEG EEG CURRENTSET ALLCOM] = eeglab;
EEG = pop_loadset('filename',[subject_list_EEG{s}],'filepath','D:\Dropbox\Jorge Flores\2023\nuevos analisis EEG humor 2023 SIFT\HH_Study\MNH_chanloc\MNH_video\seleccion componentes intra cerebrales'); %ACÁ HAY QUE PONER EL DIRECTORIO DONDE ESTÁN TODOS LOS EEG.
[ALLEEG, EEG, CURRENTSET] = eeg_store( ALLEEG, EEG, 0 );
EEG = eeg_checkset( EEG );
eeglab redraw

%EPOCAR
EEG = pop_epoch( EEG, {  '100'}, [-0.2         2], 'newname', 't epochs_ep2con epochs', 'epochinfo', 'yes');
[ALLEEG EEG CURRENTSET] = pop_newset(ALLEEG, EEG, 1,'overwrite','on','gui','off');
EEG = eeg_checkset( EEG );

% Se seleccionan épocas (1 a fin)
EEG = pop_selectevent( EEG, 'epoch',[EEG.trials] ,'deleteevents','off','deleteepochs','on','invertepochs','off');
[ALLEEG EEG CURRENTSET] = pop_newset(ALLEEG, EEG, 1,'setname','1aFin','gui','off');
eeglab redraw

% Guarda archivo
EEG = pop_saveset( EEG,'filename', [subject_list_EEG{s},'_1aFin.set'], 'filepath','D:\Dropbox\Jorge Flores\2023\nuevos analisis EEG humor 2023 SIFT\HH_Study\MNH_chanloc\MNH_video\seleccion componentes intra cerebrales\1a20');
[ALLEEG EEG] = eeg_store(ALLEEG, EEG, CURRENTSET);

end